# Generated by Django 3.2 on 2023-03-15 07:03

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_auto_20230315_0657"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=markdownfield.models.MarkdownField(
                default=True, rendered_field="text_rendered"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="text_rendered",
            field=markdownfield.models.RenderedMarkdownField(default=True),
            preserve_default=False,
        ),
    ]
