# Generated by Django 3.2 on 2023-03-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230315_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text_rendered',
        ),
    ]
