# Generated by Django 3.2 on 2023-03-15 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_remove_post_text_rendered"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="text",
        ),
    ]
