# Generated by Django 3.2 on 2023-03-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_trash"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="display",
            field=models.BooleanField(default=False),
        ),
    ]
