# Generated by Django 3.2 on 2023-03-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_auto_20230317_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="delete_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
