# Generated by Django 3.2 on 2023-03-21 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0016_alter_post_delete_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "like",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Like"
                    ),
                ),
                (
                    "dislike",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Dislike"
                    ),
                ),
                ("is_liked", models.BooleanField(default=False)),
                ("is_disliked", models.BooleanField(default=False)),
                ("is_neutral", models.BooleanField(default=True)),
                (
                    "liker",
                    models.ForeignKey(
                        blank=True,
                        help_text="The owner of this like.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
