# Generated by Django 3.2 on 2023-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to='%D-%M-%Y/', verbose_name='Head Image'),
        ),
    ]
