# Generated by Django 3.2 on 2023-04-02 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0024_alter_image_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-pk"]},
        ),
    ]
