# Generated by Django 3.2 on 2023-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0027_alter_post_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                null=True,
                upload_to="blog/%H-%M-%S/%Y-%m-%d/",
                verbose_name="Head Image",
            ),
        ),
    ]
