# Generated by Django 3.2 on 2023-04-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20230421_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voke',
            name='downvoke',
        ),
        migrations.RemoveField(
            model_name='voke',
            name='upvoke',
        ),
        migrations.RemoveField(
            model_name='voke',
            name='user',
        ),
        migrations.AddField(
            model_name='voke',
            name='post',
            field=models.OneToOneField(blank=True, help_text='The owner of this like.', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='voke',
            name='table',
            field=models.CharField(max_length=100, null=True, verbose_name='Table'),
        ),
    ]
