# Generated by Django 3.2 on 2023-04-22 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_auto_20230422_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voke',
            name='post',
        ),
        migrations.AddField(
            model_name='voke',
            name='entry_pk',
            field=models.PositiveIntegerField(help_text='The primary key of an entry eg comment or post, etc.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='voke',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The owner of this like.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
