# Generated by Django 3.2 on 2023-04-22 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20230422_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voke',
            name='is_neutral',
        ),
    ]
