# Generated by Django 3.2 on 2023-04-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_voke_is_neutral'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('text', models.TextField(null=True, unique=True, verbose_name='About Blog')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
