# Generated by Django 3.2 on 2023-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0007_auto_20230403_2132"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Postal code"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="State/Province"
            ),
        ),
    ]
