# Generated by Django 3.2 on 2023-04-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_blog',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='About Blog'),
        ),
    ]
